name: gita_companion_app
description: Gita Companion Flutter client.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.0.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  just_audio: ^0.9.46
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  animations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/data/gita_verses_sample.json
